apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pv
  namespace: orderly
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
